"""added new cols for several tables

Revision ID: abe6e2cae79c
Revises: 
Create Date: 2021-07-20 19:02:02.851846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abe6e2cae79c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_BS_name'), 'BS', ['name'], unique=True)
    op.create_table('classifer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_classifer_name'), 'classifer', ['name'], unique=True)
    op.create_table('dataset',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('feature_count', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=64), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('file_path', sa.String(length=120), nullable=True),
    sa.Column('dataset_type', sa.Integer(), nullable=True),
    sa.Column('uri_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_type'], ['datatype.id_dtype'], ),
    sa.ForeignKeyConstraint(['uri_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_dataset_name'), 'dataset', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dataset_name'), table_name='dataset')
    op.drop_table('dataset')
    op.drop_index(op.f('ix_classifer_name'), table_name='classifer')
    op.drop_table('classifer')
    op.drop_index(op.f('ix_BS_name'), table_name='BS')
    op.drop_table('BS')
    # ### end Alembic commands ###
