"""add about me

Revision ID: c0784e54f324
Revises: abe6e2cae79c
Create Date: 2021-07-26 17:12:00.271301

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c0784e54f324'
down_revision = 'abe6e2cae79c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_BS_name'), 'BS', ['name'], unique=True)
    op.drop_index('id', table_name='bs')
    op.drop_index('ix_BS_name', table_name='bs')
    op.drop_table('bs')
    op.add_column('user', sa.Column('about_me', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about_me')
    op.create_table('bs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('modified_date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_BS_name', 'bs', ['name'], unique=False)
    op.create_index('id', 'bs', ['id'], unique=False)
    op.drop_index(op.f('ix_BS_name'), table_name='BS')
    op.drop_table('BS')
    # ### end Alembic commands ###
